### ISSUE TITLE
Movie cast is not populated any more

### ISSUE THREAD

**Issue by ramusus** [alberanid/imdbpy#126] opened 2018-02-06 21:54 UTC
#### Issue description

Cast key of `movie.data` is not populated any more

#### Version of IMDbPY, Python and OS

Python 3.5.2
6.3dev20180107

#### Steps to reproduce the issue

```
In [32]: from imdb import IMDb

In [33]: ia = IMDb()

In [34]: m = ia.get_movie('0133093')

In [35]: m.data['director']
Out[35]: 
[<Person id:0905154[http] name:_Wachowski, Lana_>,
 <Person id:0905152[http] name:_Wachowski, Lilly_>]

In [36]: m.data['cast']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-36-b7b91f7b30bb> in <module>()
----> 1 m.data['cast']

KeyError: 'cast'
```

**Comment by alberanid** [comment] 2018-02-07 18:40
hi @ramusus , thatks for the report.
I guess it's caused by #103

**Comment by ramusus** [comment] 2018-02-07 20:16
Yeah, @alberanid, it seems so. Do you have any test for `cast` functionality? I didn't find it as well, as any traces of this key in the code. I can help to fix it

**Comment by alberanid** [comment] 2018-02-08 20:02
Fixed in master; not completely sure that the output is always correct, but at least now it returns something.

**Closed** 2018-02-08 20:01 UTC

**Comment by ramusus** [comment] 2018-02-08 20:59
thanks, working now
