### ISSUE TITLE
Bug while using get_movie method

### ISSUE THREAD

**Issue by nickrinaldi88** [alberanid/imdbpy#236] opened 2019-09-10 00:26 UTC
#### Issue description

There is a bug in the IMDbPY library when I try using the get_movie method

#### Version of IMDbPY, Python and OS

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
- **OS:** `python -c 'import platform ; print(platform.uname())'`

#### Steps to reproduce the issue

    import imdb
    i = imdb.IMDb()
    m = i.get_movie('0133093')

#### What's the expected result?

Posting data about the movie with the given ID

#### What's the actual result?

    Message: '%s: unable to gather refs: %s'

#### Additional details

-

**Comment by alberanid** [comment] 2019-09-14 19:25
Thanks for the report; I'm unable to reproduce.

Which version of IMDbPY are you using? Please use the version from this repository for the latest fixes.

To know the used version, run `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2 (not recommended and not supported), `python -c 'import imdb ; print(imdb.VERSION)'`

**Comment by nickrinaldi88** [comment] 2019-09-20 12:31
Hello, the line of code you told me to run isn't working for me.

I am a novice python programmer, apologies for the naivety,

Let me find the version I am running. Could you link me to the repository
you are talking about?

Also: the bug I reported works fine on my windows OS PC. On my macbook
laptop is where I am getting the errors.

Thanks!

**Comment by alberanid** [comment] 2019-09-21 08:04
This is the repository. https://github.com/alberanid/imdbpy

To install it using pip3: `pip3 install https://github.com/alberanid/imdbpy/archive/master.zip`

To clone and install it manually:
```
git clone https://github.com/alberanid/imdbpy.git
cd imdbpy
python3 setup.py install
```

**Comment by moviedatascience** [comment] 2020-01-03 05:00
I ran the above code in a colab notebook and it seems to function without issue. The get_movie function returns a Movie id and title. (In this case, The Matrix)

**Comment by alberanid** [comment] 2020-01-04 09:51
thanks for the tests. Closing it for now.  If the problem persists, please reopen it providing a test case.

**Closed by alberanid** 2020-01-04 09:51 UTC
Labels: bug, http

**Comment by nickrinaldi88** [comment] 2020-01-04 21:59
I fixed the issue. Thanks for the help.
