### ISSUE TITLE
get_movie method giving different result than get_top250_movies method

### ISSUE THREAD

**Issue by d0mk** [alberanid/imdbpy#248] opened 2020-01-01 23:52 UTC
#### Issue description

Movie object retrieved by taking n-th element of get_top250_movies result differs from the Movie object retrieved by calling get_movie method with that n-th element's ID.

Number of available keys on these objects differs (11 vs 66 when tested on the first element of get_top250_movies result, which is 'The Shawshank Redemption').

For example, I can't get the value of 'directors' key on the Movie object retrieved by getting an element from get_top250_movies method's result, but I can get that value from the Movie object retrieved by calling get_movie method with the same ID (as shown in the code below).

#### Version of IMDbPY, Python and OS

- **Python:** 3.7.6
- **IMDbPY:** 6.9dev20191224
- **OS:** uname_result(system='Windows', node='DESKTOP-RGE31E1', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')

#### Steps to reproduce the issue

```
from imdb import IMDb
ia = IMDb()
top250_movies = ia.get_top250_movies()
top_movie_v1 = top250_movies[0]
top_movie_v2 = ia.get_movie(top_movie_v1.getID()) # using the id of previous movie
print(top_movie_v1['directors']) # causes a KeyError exception
print(top_movie_v2['directors']) # prints a list of Person objects
```

**Comment by alberanid** [comment] 2020-01-04 09:58
Hi @d0mk , thanks for the report.

This is not a bug, but the intended behaviour.

Basically: doing a search or getting a list of movies with get_top250_movies or iterating over the filmography of an actor, the Movie object that you get contains just the information that were available when the object was created.
Most of the times, it's the title, movieID, year of release and little else (maybe an AKA or some notes).
Once you have a movie object with such limited amount of information, you can always fetch the main details with something like `ia.update(movieObject)`; the `update` method also allows for an extra parameter, to specify exactly which kind of information you want to retrieve (by default, only main e plot pages are parsed).

See https://imdbpy.readthedocs.io/en/latest/usage/data-interface.html for more details.

I'm closing this issue; if I've misunderstood something feel free to reopen it.

**Closed by alberanid** 2020-01-04 09:58 UTC
Labels: http
