### ISSUE TITLE
ingesting in mysql causes  mysql exception 1170

### ISSUE THREAD

**Issue by guillaumedsde** [alberanid/imdbpy#197] opened 2018-12-18 11:53 UTC
#### Issue description

ingesting in mysql causes  mysql exception 1170, see stacktrace below  for full details

#### Version of IMDbPY, Python and OS

- **Python:** `python3.7.1`
- **IMDbPY:** `6.6'` (using ingest script from repo, same time as this comment)
- **OS:** `Alpine Linux 3.8'` (mysql official docker image)

#### What's the actual result?

```
INFO:root:begin processing file /ingest/imdb_data/title.ratings.tsv.gz
INFO:root:processed 100% of file /ingest/imdb_data/title.ratings.tsv.gz: 899015 entries
INFO:root:begin processing file /ingest/imdb_data/title.principals.tsv.gz
INFO:root:processed 100% of file /ingest/imdb_data/title.principals.tsv.gz: 31326532 entries
INFO:root:begin processing file /ingest/imdb_data/title.episode.tsv.gz
ERROR:root:error processing data: 10000 entries lost: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: 'INSERT INTO title_episode (`seasonNumber`, tconst, `parentTconst`, `episodeNumber`) VALUES (%s, %s, %s, %s)'] [parameters: ((1, 41951, 41038, 9), (1, 42816, 989125, 17), (None, 42889, 989125, None), (3, 43426, 40051, 42), (2, 43631, 989125, 16), (2, 43693, 989125, 8), (3, 43710, 989125, 3), (1, 44093, 959862, 6)  ... displaying 10 of 10000 total bound parameter sets ...  (3, 463480, 497480, 2), (1, 463481, 497480, 7))] (Background on this error at: http://sqlalche.me/e/e3q8)
INFO:root:processed 99% of file /ingest/imdb_data/title.episode.tsv.gz: 3740862 entries
INFO:root:begin processing file /ingest/imdb_data/title.crew.tsv.gz
INFO:root:processed 100% of file /ingest/imdb_data/title.crew.tsv.gz: 5484158 entries
INFO:root:begin processing file /ingest/imdb_data/title.basics.tsv.gz
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1170, "BLOB/TEXT column 'titleType' used in key specification without a key length")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./s32imdbpy.py", line 185, in <module>
    import_dir(dir_name, engine)
  File "./s32imdbpy.py", line 170, in import_dir
    import_file(fn, engine)
  File "./s32imdbpy.py", line 142, in import_file
    metadata.create_all(tables=[table])
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 796, in visit_table
    self.traverse_single(index)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 823, in visit_index
    self.connection.execute(CreateIndex(index))
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/root/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/root/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1170, "BLOB/TEXT column 'titleType' used in key specification without a key length") [SQL: 'CREATE INDEX `ix_title_basics_titleType` ON title_basics (`titleType`)'] (Background on this error at: http://sqlalche.me/e/e3q8)
```

#### Additional details

-

**Comment by alberanid** [comment] 2019-01-13 15:42
I'm able to reproduce it, but at the moment I can't find a solution.  If anyone with some experience with SQLAlchemy and MySQL can help, the code to fix is in the build_table function of the s32imdbpy.py script.

**Comment by MikeSouto** [comment] 2019-05-05 09:47
I have the same problem. My specs are:
- Ubuntu 18.04
- Python 3.6.7
- pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
- imdbpy 6.6

**Comment by japrine** [comment] 2019-05-16 02:24
Same problem here.

From what I read in the mysql doc to make a TEXT column a index (which is allowed for a InnoDB table) you have to specify it as a FULLTEXT INDEX.

'CREATE INDEX ix_title_akas_title ON title_akas (title)'
should be:
'CREATE FULLTEXT INDEX ix_title_akas_title ON title_akas (title)'

I was able to create the index manually using this, but it still errors when I run the d32imdbpy because it still tries to create it again anyway.. 

I went looking for the code to fix the problem but its actually a SQlAlchemy problem and not imdbpy. 
 
One fix would be to make title a VARCHAR column instead of TEXT so it could be indexed normally.  I think the max length supported for a VARCHAR index is 767 bytes for a InnoDB, which is 383 characters so that should be enough for any title?

A alternative is to just leave it as TEXT and set index to False in the DB_TRANSFORM mapping in the imdb/parser/d3/utils.py so create_all doesn't attempt to create the index, then use a custom DDL with sqlalchemy to make the FULLTEXT index on the title column afterward.  According to the MySQL docs, making the FULLTEXT index after the data is loaded into the table is actually much faster for large data sets anyway.

**Comment by alberanid** [comment] 2019-05-19 11:26
I'm no longer able to reproduce this using the version from the master branch.

I'm using **PyMySQL** (`pip3 install PyMySQL` to install the module) with this command line:

`s32imdbpy.py /path/to/imdb-dataset-2019-05-19/ 'mysql+pymysql://username:password@localhost/imdbs3?charset=utf8' --verbose`

I've previously created the **imdbs3** database to use the *utf8_unicode_ci* collation.

Can someone try to confirm this?

**Comment by alberanid** [comment] 2020-05-17 05:53
Closed for inactivity.  If this happens again, please reopen.

**Closed by alberanid** 2020-05-17 05:53 UTC
Labels: bug, help needed, s3
