### ISSUE TITLE
Can only get episode data for the current season

### ISSUE THREAD

**Issue by mijofa** [alberanid/imdbpy#167] opened 2018-07-01 03:03 UTC
#### Issue description

When query data on all the episodes of a given show, I'm only able to get data for the current season.

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.4.2
- **IMDbPY:** 6.6dev20180624    Latest version of the master branch at time of writing
- **OS:** ('Linux', REDACTED, '3.16.0-4-amd64', '#1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19)', 'x86_64', '')    Debian 8 "Jessie"

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python3
import imdb
im = imdb.IMDb()
elementary = im.get_movie(2191671)
im.update(elementary, 'episodes')
seasons = elementary.get('episodes').keys()
```

#### What's the expected result?

- dict_keys([1,2,3,4,5,6])

#### What's the actual result?

- dict_keys([6])

**Comment by uyar** [comment] 2018-07-01 13:57
Duplicate of #160. I'll look into this shortly.

**Closed by uyar** 2018-07-01 13:57 UTC
