### ISSUE TITLE
SSL handshake failure

### ISSUE THREAD

**Issue by rednibia** [alberanid/imdbpy#155] opened 2018-05-01 20:36 UTC
#### Issue description

*write the description here*

There appears to be some sort of requests handshake issue:

All matching attempt leads to this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/IMDbPY-6.6.dev20180501-py3.6.egg/imdb/parser/http/__init__.py", line 183, in retrieve_unicode
    uopener = self.open(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1763, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1936, in open_http
    return self._open_generic_http(http.client.HTTPConnection, url, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1932, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1948, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/local/lib/python3.6/urllib/request.py", line 2136, in http_error_302
    headers, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 2167, in redirect_internal
    return self.open(newurl)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1763, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1967, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1916, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] [Errno socket error] EOF occurred in violation of protocol (_ssl.c:833)

#### Version of IMDbPY, Python and OS

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
- **OS:** `python -c 'import platform ; print(platform.uname())'`

python - Python 3.6.5rc1
imdbpy - 6.6dev20180415
OS - uname_result(system='Linux', node='ushapld00167.stg-tfayd.com', release='2.6.32-573.26.1.el6.x86_64', version='#1 SMP Tue May 3 12:39:43 PDT 2016', machine='x86_64', processor='x86_64')
#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

# your code here
```
ia = imdb.IMDb()
ia.set_proxy(proxy)
results = ia.search_movie(title)

#### What's the expected result?

-A search for movies.

#### What's the actual result?

- SSL handshake issues.

#### Additional details

- I've attempting force reinstalling every module I can think of.

**Comment by rednibia** [comment] 2018-05-02 18:03
Appears to have gone away on its own.

**Comment by alberanid** [comment] 2018-05-06 08:38
Hi, thanks for the report.  It seems to happen, every now and then; it would be cool if someone is able to reproduce it.

**Comment by rednibia** [comment] 2018-05-18 20:47
Same error on that code you gave:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_imdb.py", line 16, in <module>
    uo.open('https://www.imdb.com/title/tt0133093/reference').read()
  File "/usr/local/lib/python3.6/urllib/request.py", line 1763, in open
    raise OSError('socket error', msg).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.6/urllib/request.py", line 1757, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1967, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1916, in _open_generic_http
    http_conn.request("GET", selector, headers=headers)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:833)

FYI - I'm using a proxy if that matters.

**Comment by alberanid** [comment] 2018-05-19 11:49
@rednibia : thanks for the report!

So, on your system the problem is always reproducible?

What kind of proxy do you have?  https?  Can you do a test without it?

Thanks!

**Comment by rednibia** [comment] 2018-05-21 21:12
http proxy

Without it, I'm getting an error:

 'exception type': 'IOError', 'original exception': OSError('socket error', gaierror(-2, 'Name or service not known'))},); kwds: {}

I've also seen this error:

'Internal Server Error: Redirect Recursion'

**Comment by alberanid** [comment] 2018-05-21 21:57
@rednibia : "Name or service not known" seems a DNS problem.

What's your operating system?  Is it fully updated?  Python version?

I admit I'm a little baffled by this bug, right now. :-/

Thanks for your help!

**Comment by rednibia** [comment] 2018-05-22 16:26
Python 3.6, Linux Redhat. Honestly don't know all the configuration information, but it hasn't changed in the last few months and the API calls has since stopped working.

Name or service not known is something I got before without the proxy, even before the SSL issue, so I don't think it's related to anything.

Is it possible that too many API calls got my IP banned or something?

**Comment by alberanid** [comment] 2018-06-24 07:57
after more reports, I've just committed to master a change that completely disable certificate validation.
It seems that for some reason some users are served invalid certificates.

**Comment by alberanid** [comment] 2018-07-08 16:47
I've just pushed on master a version (6.6dev20180708) with a complete fix for the SSL certificate problems.

Tested on a VM where I removed /etc/ssl, and it works on both Python 2.7 and 3.5.

As always, any feedback is welcome.

Thanks!

**Comment by alberanid** [comment] 2018-08-05 14:07
I've just released IMDbPY 6.6 that should fix this issue.

**Closed by alberanid** 2018-08-05 14:07 UTC
Labels: bug, http
