### ISSUE TITLE
NULL movie_id in move_link file

### ISSUE THREAD

**Issue by beanumber** [alberanid/imdbpy#35] opened 2016-04-04 19:14 UTC
```
 * LOADING CSV FILE /home/bbaumer/dumps/imdb/raw/movie_link.csv...
ERROR: unable to import CSV file /home/bbaumer/dumps/imdb/raw/movie_link.csv: null value in column "movie_id" violates not-null constraint
DETAIL:  Failing row contains (14300, null, 95357, 12).
CONTEXT:  COPY movie_link, line 14300: "14300,NULL,95357,12"
```

Using PostgreSQL and a recent copy of the data files.

**Comment by alberanid** [comment] 2016-04-17 18:58
are you using the version from the repository?

I'm trying to reproduce it, but so far it works (MySQL, csv option, a recent dump of the files).


Thanks for your report!

**Comment by alberanid** [comment] 2018-02-13 21:46
Closing this, since IMDb stopped updating the old dataset and the new one is much easier to parse and import.

See the new 's3' data parser.

**Closed by alberanid** 2018-02-13 21:46 UTC
Labels: bug, sql
