### ISSUE TITLE
TV Show Episode Ratings are not parsing - 'episodes rating' not being updated

### ISSUE THREAD

**Issue by pgjensen** [alberanid/imdbpy#123] opened 2018-01-19 02:56 UTC
#### Issue description

'episodes rating' is no longer pulling in ratings for individual episodes.

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.5.2
- **IMDbPY:** latest master 1/17/2018 - IMDbPY-6.3.dev20180117-py3.5.egg
- **OS:** Ubuntu 16.04.3

#### Steps to reproduce the issue

Pull in a TV Show and update both 'episodes' and 'episodes rating' - data is not parsed for episodes rating

```
#!python
        import imdb
        i = imdb.IMDb('http')
        imdb_data = i.get_movie("5770786")
        i.update(imdb_data, 'episodes')
        i.update(imdb_data, 'episodes rating')
        print(imdb_data['episodes'])
        print(imdb_data['episodes rating'])

# your code here
```

#### What's the expected result?

episodes rating should print out data

#### What's the actual result?

doesn't contain data

#### Additional details

Individual episodes do have 'rating' info when accessed directly using get_movie('6016432')

**Comment by alberanid** [comment] 2018-01-19 08:10
Hi,
both this and #121 are probably consequences of #103 

I told that I wanted to work on the series/episodes parsers, but between #60 and other project, I fear I will not be able to fix them very soon. :-/

**Comment by alberanid** [comment] 2018-02-25 10:58
fixed removing the parser, since they deleted the specific page.

The same information can now be fetched in this way:

```
from imdb import IMDb
ia = IMDb()

series = ia.get_movie('5770786')
ia.update(series, 'episodes')
for season_nr in sorted(series['episodes']):
    for episode_nr in sorted(series['episodes'][season_nr]):
        episode = series['episodes'][season_nr][episode_nr]
        print('episode #%s.%s; rating: %s; votes: %s' %
              (season_nr, episode_nr, episode.get('rating'), episode.get('votes')))
```

**Comment by italo-batista** [comment] 2018-05-24 03:36
@alberanid Thanks for sharing this code above! :smiley: 
Do you know any way to get episodes for all seasons?  When I do `ia.update(series, 'episodes')`, just the episodes from the _default_ season (first season showed in tv show episodes list page)  are updated in object. Thanks!

**Comment by CGraabaek** [comment] 2019-05-08 06:03
@alberanid 

> fixed removing the parser, since they deleted the specific page.
> 
> The same information can now be fetched in this way:
> 
> ```
> from imdb import IMDb
> ia = IMDb()
> 
> series = ia.get_movie('5770786')
> ia.update(series, 'episodes')
> for season_nr in sorted(series['episodes']):
>     for episode_nr in sorted(series['episodes'][season_nr]):
>         episode = series['episodes'][season_nr][episode_nr]
>         print('episode #%s.%s; rating: %s; votes: %s' %
>               (season_nr, episode_nr, episode.get('rating'), episode.get('votes')))
> ```

When i try this code, I cannot get any ratings for episodes. 

When I look at the documentation it says: 

_You can retrieve rating information about every episode in a TV series or mini series using the 'episodes rating' data set._ but I cannot seem to get this to work either. 

How do I get this to work?

**Comment by reggie84** [comment] 2019-05-20 20:07
Having the same issue with rating: 
episode #1.1; rating: None; votes: 1151
episode #1.2; rating: None; votes: 980
episode #1.3; rating: None; votes: 901

series['episodes'][1][1].get('rating') = empty

I guess I'm reading the docs wrong:
ia.update(got, 'episodes rating')
2019-05-20 17:01:58,235 ERROR [imdbpy] /usr/local/lib/python3.7/site-packages/imdb/__init__.py:705: unknown information set "episodes rating"

**Comment by alberanid** [comment] 2019-05-20 21:01
reopening so that we can work again on this.

**Comment by alberanid** [comment] 2019-05-21 17:06
it was probably just a side-effect of #210 . The proposed code works for me:
```
episode #1.1; rating: 7.901234567891; votes: 1151
episode #1.2; rating: 7.601234567891; votes: 980
episode #1.3; rating: 7.801234567891; votes: 901
episode #1.4; rating: 7.701234567891; votes: 871
episode #1.5; rating: 8.101234567891; votes: 848
episode #1.6; rating: 7.801234567891; votes: 811
episode #1.7; rating: 8.401234567891; votes: 861
episode #1.8; rating: 8.001234567891; votes: 821
episode #1.9; rating: 8.201234567891; votes: 806
episode #1.10; rating: 8.801234567891; votes: 904
episode #2.1; rating: 8.001234567891; votes: 670
episode #2.2; rating: 7.801234567891; votes: 610
episode #2.3; rating: 7.801234567891; votes: 594
episode #2.4; rating: 8.701234567891; votes: 694
episode #2.5; rating: 8.301234567891; votes: 592
episode #2.6; rating: 8.701234567891; votes: 630
episode #2.7; rating: 8.701234567891; votes: 667
episode #2.8; rating: 8.501234567891; votes: 941
episode #2.9; rating: 8.501234567891; votes: 583
episode #2.10; rating: 9.201234567891; votes: 752
episode #3.1; rating: None; votes: None
episode #3.2; rating: None; votes: None
episode #3.3; rating: None; votes: None
episode #3.4; rating: None; votes: None
episode #3.5; rating: None; votes: None
episode #3.6; rating: None; votes: None
episode #3.7; rating: None; votes: None
episode #3.8; rating: None; votes: None
episode #3.9; rating: None; votes: None
episode #3.10; rating: None; votes: None
```

(ok, the None for a still unaired episode are not nice, but...)

**Comment by reggie84** [comment] 2019-05-21 17:48
After updating with repo version I can confirm that the proposed code works for me too.
I don't think the none for unaired episodes is a problem.
Thanks!!

**Comment by alberanid** [comment] 2019-05-22 21:04
thanks for the test, I'm closing this issue for now.

**Closed by alberanid** 2019-05-22 21:04 UTC
Labels: bug, http
