### ISSUE TITLE
Unable to find the crew information

### ISSUE THREAD

**Issue by VarshaMaragi** [alberanid/imdbpy#125] opened 2018-02-02 07:30 UTC
#### Issue description

I am unable to get the crew information with the latest imdbpy.
I have already tried updating the movie object and tried getting infoset.
None of the keys have information about behind the camera.Ex:producer,music by,cinematography etc

#### Version of IMDbPY, Python and OS

- **Python:** `Python 3.5.2` 
- **IMDbPY:** `6.3dev20180107`
- **OS:** `Ubuntu `

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by alberanid** [comment] 2018-02-07 18:41
hi @VarshaMaragi , I guess it's caused by #103

**Comment by alberanid** [comment] 2018-02-09 13:57
should be fixed in master.

**Closed by alberanid** 2018-02-09 13:57 UTC
