### ISSUE TITLE
IMDb redesign broke most of the parsers on Dec. 19, 2017

### ISSUE THREAD

**Issue by itsayellow** [alberanid/imdbpy#103] opened 2017-12-20 21:23 UTC
#### Issue description

For the past couple of days, fetching information with imdpy is broken.  For example, using the doc example of fetching data for "The Untouchables" yields a title of 'The leading information resource for the entertainment industry'

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.6.4
- **IMDbPY:** 6.2
- **OS:** uname_result(system='Darwin', node='arioso', release='15.6.0', version='Darwin Kernel Version 15.6.0: Mon Nov 13 21:58:35 PST 2017; root:xnu-3248.72.11~1/RELEASE_X86_64', machine='x86_64', processor='i386')

#### Steps to reproduce the issue

```
>>> import imdb
>>> ia = imdb.IMDb()
>>> s_result = ia.search_movie("The Untouchables")
>>> the_unt = s_result[0]
>>> ia.update(the_unt)
>>> the_unt['runtime']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/imdb/utils.py", line 1480, in __getitem__
    rawData = self.data[key]
KeyError: 'runtimes'
>>> the_unt['rating']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/imdb/utils.py", line 1480, in __getitem__
    rawData = self.data[key]
KeyError: 'rating'
>>> the_unt['title']
'The leading information resource for the entertainment industry'
>>> the_unt.keys()
['title', 'kind', 'year', 'akas', 'plot', 'canonical title', 'long imdb title', 'long imdb canonical title', 'smart canonical title', 'smart long imdb canonical title']
>>> the_unt['kind']
'movie'
>>> the_unt['year']
2017
>>> the_unt['akas']
['The Untouchables']
>>> the_unt['plot']
["A comedic look at the relationship between a wealthy paraplegic and an unemployed man with a criminal record who's hired to help him."]
>>> the_unt['canonical title']
'leading information resource for the entertainment industry, The'
>>> the_unt['long imdb title']
'The leading information resource for the entertainment industry (2017)'
```

#### What's the expected result?

- real movie data

#### What's the actual result?

- random marketing strings for imdb.com, or missing key errors of internal data

#### Additional details

-

**Comment by itsayellow** [comment] 2017-12-20 22:03
Most movies I search for return titles of: 'The leading information resource for the entertainment industry' and no plot outline.  Many other keys are missing.
The year seems to continue to work fine.

**Comment by heyoni** [comment] 2017-12-21 05:20
With all that's going on with IMDB and the fact that they're seriously narrowing what information we can get from their data dumps, it could be that they're walling off their database.

I really hope that's not the case but this could be deliberate.

**Comment by SanderTuit** [comment] 2017-12-21 09:46
@heyoni I don't think that's the case. All information is still present and it seems to be organized even better. However, it seems that there are a lot of changes that need to be made in movieParser.py.

I have limited experience with imdbpy and no experience with XPath, but the title can be fixed by changing the path for the title to `path="//h1[@itemprop='name']"`. The cast list can be fixed by changing the cast path to `path="//table[@class='cast_list']//tr"`.

**Comment by SanderTuit** [comment] 2017-12-21 15:02
@alberanid I'd like to contribute some fixes, but I'm new to this. Perhaps you can tell me why this doesn't work: 

`Extractor(
            label='thin director',
            path="//span[@itemprop='director']",
            attrs=Attribute(
                key='thin director',
                multi=True,
                path={
                    'name': "./a/span[@itemprop='name']/text()",
                    'link': "./a/@href"
                },
                postprocess=lambda x: build_person(
                    x.get('name') or '',
                    personID=analyze_imdbid(x.get('link'))
                )
            )
        ),`

or this:

`Extractor(
            label='cover url',
            path="//div[@class='poster']/a",
            attrs=Attribute(
                key='cover url',
                path="./img/@src"
            )
        )`

so I can apply this to other fields and make a pull request.

**Comment by heyoni** [comment] 2017-12-21 22:18
@SanderTuit I just realized why what I said doesn't make any sense. Unlike imdb-pie, imdbpy is actually scraping the web.

**Comment by alberanid** [comment] 2017-12-23 08:20
@heyoni IMDb seems to be willing to (re)introduce more data in the S3 dataset, but I don't expect it too soon (anyway, it's a good idea to start working on a parser for that).

@jsynowiec I think that a (slightly) safer option would be **//h3[@itemprop='name']**

@SanderTuit I'll try to look at it: it seems there are many changes. :-/

For everyone: thanks to @uyar we have a testsuite that you can run using **tox**.

**Comment by heyoni** [comment] 2017-12-23 09:15
@alberanid the data sets on amazon s3 are missing lots of information, like release dates and full cast. Just yesterday, Col Needham copy/pasted an old reply of his stating that only certain contributors would get the full data dumps, and everyone else gets imdb lite.

https://getsatisfaction.com/imdb/topics/imdb-data-now-available-in-amazon-s3?utm_source=notification&utm_medium=email&utm_campaign=new_comment&utm_content=reply_button&reply[id]=19185837#reply_19185837

**Comment by randomrandom** [comment] 2017-12-23 15:33
reviews are also broken

**Comment by alberanid** [comment] 2018-01-01 17:48
I've committed to master some (few) fixes for the main parser.  Unfortunately many many more are still broken.

**As always, any help is welcome.**

If you want to start fixing something, run the **tox** and chose one of the parsers you want to work on (and tell us on this issue, so that we can avoid duplicate work).
Thanks!

**Comment by enriqueav** [comment] 2018-01-06 22:54
@SanderTuit I also lost 2-3 hours trying things with XPath and inadvertently tried the exact same Extractor for Directors that you posted a couple of weeks back. The problem? We were looking at the regular URL for the movie [http://www.imdb.com/title/tt0133093](http://www.imdb.com/title/tt0133093), but imdbpy actually reads from the "reference" version, which is very different [http://www.imdb.com/title/tt0133093/reference](http://www.imdb.com/title/tt0133093/reference).

@alberanid I have created a PR which fixes the Director and Writer parsers. I can work to fix more in the next days.

**Comment by alberanid** [comment] 2018-01-07 17:24
@enriqueav : merged, thanks!  I've also added a couple to tests.

**Comment by JanDebiec** [comment] 2018-01-08 10:33
Hello,
After changes in IMDB in Dec.2017, I have developed another approach: finding the infos in IMDB's TSV files. You can check the procedure, my project is in my Repo:
https://github.com/JanDebiec/MovieDB
The tests with parsing about 600 Movies and 250 Directors were positive

**Comment by jsynowiec** [comment] 2018-01-10 10:00
In Certificates, _notes_ section is now ends up as a separate element in the list. If previous format is to be retained (the one with `::(` prefixed notes), then a standalone postprocessor for certificates is needed. Something like what I've done in https://github.com/jsynowiec/imdbpy/commit/a3f8ab58983883c5439638609c0e09f6f7b49a17
Are you interested in a PR to master with it?

**Comment by uyar** [comment] 2018-01-10 11:23
@jsynowiec In the master branch, I've added some basic tests for movie certificates. If you make them pass, that will be great, thanks! Feel free to add more tests and fix any errors I might have made in the tests.

**Comment by uyar** [comment] 2018-01-10 11:43
@JanDebiec I'm not very familiar with it but your project sounds like what IMDbPY does in its SQL access system.

**Comment by alberanid** [comment] 2018-01-10 18:35
@JanDebiec : cool!  I'll give it a look.
It's also in my plans to add support for the new S3 data sets as soon as possible (historically, IMDbPY has always supported the old plain text data files).

The idea is to import the data without much transformations (using SQLAlchemy, probably), and then develop the usual interface of IMDbPY to access the data.

Since you've already done some work on it, if you have any insight to share or you want to join the development, any help is welcome!

PS: for this specific aspect, the issue is #60

**Comment by JanDebiec** [comment] 2018-01-10 19:09
@alberanid 
My plan was to build local MovieDB with support of Imdbpy. After 20.Dec.17 I have decided  to write TSV files analyzer and here get main data for my local DB.

my project is based on Miguel's fantastic Flask tutorial.
I'm using Flask, flask-sqlalchemy, sqlite3.
The Imdb-tsv data extractor is already functioning, tested with my own db (600 movies).
Many other parts of project are in early development state, but tsv-extractor is working

I'll be glad to join your project and add my contribution.
If you want, we can communicate direct through emails, to discuss some details

**Comment by yliharma** [comment] 2018-01-11 11:20
Hi @alberanid ,
do you plan to fix also the legacy branch? 
We use imdbpy on a big Django website which runs under python2.7...

**Comment by alberanid** [comment] 2018-01-11 13:04
@yliharma : hi,
personally I don't have the energy to keep the legacy branch in sync.

It goes without saying that if someone wants to maintain it, I'll be more than glad to merge the PRs.

If someone wants to work on it, the first commit I think is https://github.com/alberanid/imdbpy/commit/1126eb49a6298e7b96d081aa069a12dc8f5965ef (basically you have to check for anything committed under the imdb/parser/http/ directory).


Thanks.

**Comment by uyar** [comment] 2018-01-16 19:04
@jsynowiec In PR #118, I've included your change to the certificates parser.

**Comment by alberanid** [comment] 2018-03-03 16:39
Since a lot of parsers are now fixed and we have introduced a way to import the new dataset, I'm closing this issue.

Please open a new issue for any parser that is still broken.

Thanks!

**Closed by alberanid** 2018-03-03 16:39 UTC
Labels: bug, help needed, http

**Comment by tlc** [comment] 2018-11-07 04:20
This is broken.  
movie.keys() should only return keys that work, not keys that might throw KeyError when used.
This breaks basic dict behavior like  my_template.format(**movie)

**Comment by alberanid** [comment] 2018-11-07 07:46
@tlc : could you provide a minimal test code to reproduce the problem? Thanks.

**Comment by tlc** [comment] 2018-11-07 22:59
```
import imdb

def myfunc(**kwargs):
      pass

objIA = imdb.IMDb()
movie = objIA.search_movie('Pitch Perfect 3')[0]
objIA.update(movie)
myfunc(**movie)
```
returns

> Traceback (most recent call last):
>   File "bug.py", line 9, in <module>
>     myfunc(**movie)
>   File "/home/tlc/.local/lib/python3.5/site-packages/imdb/utils.py", line 1495, in __getitem__
>     rawData = self.data[key]
> KeyError: 'sound crew'

I _assume_ this is because keys() should return the keys actually present in the object, not a list of keys that might be used.

You should also be able to loop over keys(), performing movie[key] without worrying about KeyError.

**Comment by jsynowiec** [comment] 2018-11-08 11:39
If you want to unpack the _raw values_, then you should use the `data` field, not the instance itself. Not all values are guaranteed to be present on the raw dict. 

```py
In [1]: from imdb import IMDb
In [2]: imdb = IMDb()
In [3]: movie = imdb.get_movie('1727824')
In [4]: def myfunc(**kwargs):
   ...:           pass
   ...:
In [5]: myfunc(**movie.data)
In [6]: movie.data['title']
Out[6]: u'Bohemian Rhapsody'
```

If you're accessing values from the instance then you should use the getter and provide either a default or handle the default `None`.

**Comment by tlc** [comment] 2018-11-08 15:11
Thanks.  I don't know what you mean when you refer to "raw values" and "raw dict", but it appears that .data works as I expect a dict to work.

Maybe there's a documentation problem?  I can't find a reference to '.data' anywhere on https://imdbpy.readthedocs.io/en/latest/ .  And the quick start docs say:

> As the examples indicate, the results are lists of Movie, Person, or Company objects. These behave like dictionaries, i.e. they can be queried by giving the key of the data you want to obtain:
> 
> >>> movies[0]['title']

But Movie, at least, doesn't quite behave like a dictionary, for the reason I've outlined.

**Comment by alberanid** [comment] 2018-11-08 15:47
@jsynowiec @tlc : **.data** is an internal (a real dictionary) and not supposed to be used by client code.

Movie objects should not contain missing keys; I'll look into it as soon as possible.  I've opened #188 - thanks for the bug report.
