### ISSUE TITLE
s32imdbpy.py hangs with PostgreSQL

### ISSUE THREAD

**Issue by ChakshuGautam** [alberanid/imdbpy#190] opened 2018-11-20 13:55 UTC
#### Issue description
s32imdbpy.py with postgres hangs after the following output

INFO:root:begin processing file ./title.ratings.tsv.gz
DEBUG:root:headers of file ./title.ratings.tsv.gz: tconst,averageRating,numVotes
DEBUG:root:building table for file title.ratings.tsv.gz

Since there is no way to check where the problem is, I am unable to debug. The PSQL is hosted on google cloudsql. I am using unix sockets to connect.

I wasn't able to poppulate data in MySQL with similar config but ran into some other problems with title_akas index for title and it didn't go further due to this error. I tried to remove the index but it didn't work either.

#### Version of IMDbPY, Python and OS

- **Python:** 3.5.3
- **IMDbPY:** 6.6
- **OS:** uname_result(system='Linux', node='imdb-cron-ip-ping', release='4.9.0-8-amd64', version='#1 SMP Debian 4.9.130-2 (2018-10-27)', machine='x86_64', processor='')

**Comment by alberanid** [comment] 2018-11-24 13:31
Unable to reproduce the problem with PostgreSQL 10.6 on a Ubuntu 18.04 :-/
Instead, I was able to reproduce the other problem with MySQL; I've opened #193 for it, thanks for the report!

Talking about PostgreSQL: how did you call the s32imdbpy.py script (i.e.: which command arguments?)

Have you tried using the version from the repository?

On my system, it took about 1.5 hours on a (busy) Intel i5-6600, but completed successfully:
```
$ python3 ./s32imdbpy.py /home/da/imdb-dataset-2018-11-24/ postgresql://username:password@localhost/imdbs3
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/title.ratings.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/title.ratings.tsv.gz: 888923 entries
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/title.crew.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/title.crew.tsv.gz: 5424031 entries
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/name.basics.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/name.basics.tsv.gz: 8973383 entries
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/title.basics.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/title.basics.tsv.gz: 5426705 entries
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/title.principals.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/title.principals.tsv.gz: 30947761 entries
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/title.episode.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/title.episode.tsv.gz: 3703363 entries
INFO:root:begin processing file /home/da/imdb-dataset-2018-11-24/title.akas.tsv.gz
INFO:root:end processing file /home/da/imdb-dataset-2018-11-24/title.akas.tsv.gz: 3691262 entries
```

**Comment by ChakshuGautam** [comment] 2018-11-26 01:29
The PSQL problem must be because of something on my end. But it seems to not get caught on the SQLAlchemy either. Anyway, I will ask Google ablout this too. I was able to use the Psql client with the same configs with ease. Thanks for the MYSQL solution. I would be using that for now.

**Comment by alberanid** [comment] 2018-12-24 10:55
@ChakshuGautam great, closing this for now.  If you encounter other problems, open a new issue.  Thanks for the report!

**Closed by alberanid** 2018-12-24 10:55 UTC
Labels: bug, s3
